
analyzer:
  errors:
    directives_ordering: ignore
    lines_longer_than_80_chars: ignore
    public_member_api_docs: ignore 
    sort_constructors_first: ignore
    unnecessary_lambdas: ignore
include: package:very_good_analysis/analysis_options.yaml
linter:

  rules:

