name: flutter_food_recipe_application
description: "A new Flutter project."

publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  connectivity_plus: ^6.0.3
  dartz: ^0.10.1
  easy_localization: ^3.0.7
  get_it: ^7.7.0
  google_fonts: ^6.2.1
  shared_preferences: ^2.2.3
  provider: ^6.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/animations/
    - assets/lang/
    - assets/sounds/

